In [ ]:
# RNNs

In [2]:
import torch

import torch.nn as nn

In [4]:
rnn = nn.RNN(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)
output, hn

(tensor([[[ 1.1047e-01,  8.0212e-01,  3.3494e-01, -4.0031e-02, -4.3812e-01,
           -3.8096e-01,  2.6905e-01,  6.4531e-01, -5.3116e-01, -6.0589e-01,
           -8.5458e-01,  1.8073e-01, -8.6270e-03, -3.9380e-01, -1.7648e-01,
            2.9953e-01, -7.8109e-01, -2.7912e-01,  4.6838e-01, -3.6760e-01],
          [ 1.9776e-01, -5.8723e-02,  3.2135e-01,  5.9932e-01, -6.1540e-01,
           -7.7013e-01,  2.9436e-01,  2.4103e-01, -8.8304e-01, -2.5290e-01,
           -9.5303e-01,  6.4847e-01,  4.7463e-02,  5.0267e-01, -8.5077e-01,
           -2.9195e-01, -6.2688e-01,  8.6363e-01,  4.5657e-01,  8.0134e-01],
          [-4.5189e-01, -8.7749e-01,  3.4172e-01,  3.0653e-01, -5.3539e-01,
           -6.4579e-02,  7.4423e-01,  3.2054e-01, -6.3828e-01,  5.9502e-01,
            4.9871e-01, -4.8939e-01, -3.4822e-01, -2.0950e-01, -5.3484e-01,
            7.4094e-01,  1.5444e-01, -1.9145e-01,  6.6311e-01,  2.4252e-01]],
 
         [[ 1.8844e-01, -7.3441e-02,  3.7596e-01,  3.3764e-01, -2.5437e-01,
      

In [5]:
rnn = nn.RNN(input_size=10, hidden_size=20, num_layers=2)
input = torch.randn(5, 3, 10)
input

tensor([[[-0.7231,  1.1541, -0.7701, -0.8618,  0.7817,  0.3089, -0.7609,
          -1.9617,  0.9870,  0.8669],
         [-2.4755, -0.2061,  0.1378,  1.6548,  1.4792,  1.1585,  1.1561,
           0.2775, -0.3662,  1.7378],
         [-0.2560,  0.5089, -0.1260, -1.3191, -0.5192,  0.8199, -0.6649,
          -0.2351,  0.5716, -0.0301]],

        [[-0.3286, -1.7393, -0.0607, -1.1257,  0.4805,  0.3206,  0.1188,
           2.3239, -1.1925,  0.6454],
         [-0.5804, -0.5374,  0.9036,  0.2244,  0.0835,  0.5997, -1.1487,
           0.4083,  0.3230, -0.1271],
         [ 0.5825,  1.4421,  0.1941, -0.8862,  0.2626, -0.6472, -0.3474,
           1.1614,  0.2983,  1.1507]],

        [[ 1.4065,  1.0115,  0.3764,  1.7744,  0.2778, -0.5555,  0.2934,
           0.6479,  0.6014,  0.3360],
         [ 0.5283, -0.0692, -0.5200,  2.4162, -1.1550, -0.1247,  0.6502,
          -0.3991, -0.2720, -1.4342],
         [ 1.6468,  2.0887,  0.0399,  0.3227, -1.1684, -0.3349, -0.8021,
          -0.5437, -0.5731, -1.1301

In [6]:
h0 = torch.randn(2, 3, 20)
h0

tensor([[[ 9.3075e-01, -3.3415e-01, -1.1785e+00, -1.4092e+00, -2.6890e-01,
          -1.0503e-01,  1.5079e+00, -9.4815e-01,  3.7378e-01, -2.5660e-01,
           4.8714e-01, -1.2662e-01,  5.5422e-01,  3.4157e-01,  1.1097e+00,
          -3.4939e-01,  1.2461e-01, -6.0592e-01, -2.0793e+00,  8.1933e-01],
         [ 6.9116e-01, -1.2544e+00,  3.5364e-01,  5.1376e-01, -8.2382e-01,
          -3.4984e-01,  2.6442e+00, -2.1813e-01,  4.4098e-01,  4.4917e-01,
          -6.1754e-01, -1.5498e+00,  1.0939e+00, -2.0461e-01, -6.6011e-01,
           7.7286e-02,  5.2907e-01,  2.6026e-01, -8.7891e-01,  1.1252e+00],
         [ 1.3808e+00, -5.5181e-01, -3.9491e-01, -2.7492e-01, -1.3428e+00,
          -1.5012e-04, -4.8338e-01,  4.5553e-01, -1.7879e+00,  5.0119e-01,
           4.9288e-03,  1.8493e-02, -1.1562e+00, -1.3524e+00,  7.0369e-01,
          -8.7926e-01,  1.1593e+00,  3.7492e-01,  3.7105e-01,  4.6092e-01]],

        [[-1.3457e-01,  8.7777e-01,  7.3377e-01,  9.5746e-01,  4.2579e-01,
           1.5978e-0

In [7]:
output, hn = rnn(input, h0)
output, hn

(tensor([[[-5.2802e-01, -4.2995e-01, -8.7983e-01,  7.5657e-01,  3.0549e-01,
           -4.6763e-01, -2.3861e-01, -5.8409e-01,  5.9299e-01, -6.7923e-02,
            3.5765e-01, -5.2450e-01,  4.6033e-01,  2.6079e-01, -9.3261e-01,
           -7.1314e-01,  2.4284e-01, -8.4711e-01, -1.7781e-01,  3.1357e-01],
          [-8.7727e-01, -7.1625e-01,  3.8914e-01,  1.6105e-01,  9.2197e-01,
           -7.8713e-01,  5.7661e-01, -5.2560e-01,  1.8681e-01, -5.3912e-02,
            7.3257e-01, -1.2594e-01, -4.4886e-01, -3.5073e-02, -7.1752e-01,
            4.2494e-01,  3.4917e-02, -4.7594e-01, -1.8843e-01,  1.0563e-01],
          [ 9.6086e-01, -4.2554e-01,  8.5596e-01, -5.1657e-01, -3.9544e-01,
           -1.0048e-01,  4.6045e-01, -4.0102e-01,  2.4361e-01,  7.8105e-01,
           -6.6225e-02,  9.1620e-01,  1.7617e-01,  5.5118e-01,  2.2531e-01,
            8.9848e-01,  2.6729e-03,  8.4285e-01,  6.9614e-01,  8.9299e-01]],
 
         [[-3.5745e-01,  1.8798e-02, -4.2245e-02,  1.3027e-01,  4.1775e-01,
      