In [1]:
import warnings
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
warnings.filterwarnings("ignore")

In [3]:
X, y = make_classification(
    n_samples=1000,       # Total number of samples
    n_features=20,        # Number of features
    n_informative=2,      # Number of informative features
    n_redundant=10,       # Number of redundant features
    n_clusters_per_class=1,
    weights=[0.905, 0.095],   # Imbalance ratio
    flip_y=0,             # No noise
    random_state=1        # Reproducibility
)
X

array([[-0.20245394,  0.75116708, -1.5118818 , ..., -1.56978108,
         0.6370882 , -0.46505859],
       [-0.2933976 , -0.4618495 , -1.03503817, ..., -1.36749482,
         0.77655426, -0.30663438],
       [-0.23353927,  1.59413738, -0.24302373, ..., -1.25174607,
         0.64451726,  0.74205658],
       ...,
       [ 0.40607453,  0.38551581, -0.68063573, ..., -0.4895647 ,
        -0.68961613,  2.60755891],
       [-0.19983642,  0.40406811,  0.1310922 , ..., -1.28099316,
         0.5854406 , -0.76433963],
       [-0.01938808, -2.10390849, -0.73355857, ...,  0.05138838,
         0.0283964 ,  0.40036396]])

In [4]:
y

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,

In [5]:
import pandas as pd
y_df = pd.DataFrame(y)
y_df.value_counts()

0
0    905
1     95
Name: count, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_train

array([[-0.34557838,  1.66577009,  0.22344646, ..., -2.07596964,
         0.98989014, -0.49064402],
       [-0.61247126, -0.38705067,  1.09473176, ..., -3.20072291,
         1.67701905, -0.26406316],
       [-0.54556375,  0.10621572, -0.46967499, ..., -2.28092333,
         1.40163521, -0.7744141 ],
       ...,
       [-0.37035672, -0.98494891,  0.37211054, ..., -2.16227975,
         1.0507548 ,  0.48125579],
       [-0.17246383,  0.81598915, -1.04096285, ..., -0.62749115,
         0.42795918, -1.2514994 ],
       [-0.71869   ,  0.46962505,  0.90851022, ..., -2.84019122,
         1.8198179 , -0.45487402]])

In [7]:
X_test

array([[-0.40928132, -0.9128003 ,  0.1445099 , ..., -1.84846401,
         1.07370717,  0.58337653],
       [ 0.77275085,  0.81660994,  1.1971909 , ...,  1.03978201,
        -1.63106863,  0.0176911 ],
       [-0.33444524,  0.14570852, -0.35551547, ..., -1.21890562,
         0.83024027, -1.67220853],
       ...,
       [-0.57641738,  0.53336746,  0.91944718, ..., -2.39288702,
         1.47814921,  0.60736615],
       [-0.54646228, -0.61770719, -0.39996   , ..., -2.55389826,
         1.44747175,  0.42040338],
       [-1.07224546, -1.30250786,  0.37011284, ..., -4.52216092,
         2.76110686, -0.99690494]])

In [ ]:
class_weights = []
# custom_class_weight_1 = {A: 10, B: 1}
custom_class_weight_2 = {A: 1, B: 10}
custom_class_weight_3 = {A: 1.5, B: .75}


class_weights.append('balanced')
class_weights.append(custom_class_weight_1)
class_weights.append(custom_class_weight_2)
class_weights.append(custom_class_weight_3)
class_weights

['balanced', {0: 10, 1: 1}, {0: 1, 1: 10}, {0: 1.5, 1: 0.75}]

In [11]:
for class_weight in class_weights:
    # print("="*70)
    print(f"\t\tclass_weight: {class_weight}")
    model = LogisticRegression(class_weight=class_weight, max_iter=1000, solver='lbfgs')
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    # Evaluate the model
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("="*70)

		class_weight: balanced
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       179
           1       0.49      0.81      0.61        21

    accuracy                           0.89       200
   macro avg       0.73      0.85      0.77       200
weighted avg       0.92      0.89      0.90       200

Confusion Matrix:
[[161  18]
 [  4  17]]
		class_weight: {0: 10, 1: 1}
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       179
           1       1.00      0.81      0.89        21

    accuracy                           0.98       200
   macro avg       0.99      0.90      0.94       200
weighted avg       0.98      0.98      0.98       200

Confusion Matrix:
[[179   0]
 [  4  17]]
		class_weight: {0: 1, 1: 10}
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.89      0.93       179
 