In [1]:
import os
import sys

import pandas as pd

from IPython.display import Image

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from feature_extraction import TfidfFeatureExtraction, SpacyFeatureExtraction

In [2]:
import pandas as pd

# Example DataFrame
df_to_vectorize = pd.DataFrame({'text': ["This is a test sentence.", "Another sentence for testing."]})
df_to_vectorize

text
0       This is a test sentence.
1  Another sentence for testing.

In [3]:
# # Create instances of the feature extraction classes
# tfidf_extractor = TfidfFeatureExtraction(df_to_vectorize, 'text')
# # Extract TF-IDF scores
# tfidf_scores_df = tfidf_extractor.feature_scores()
# tfidf_scores_df

In [4]:
# spacy_extractor = SpacyFeatureExtraction(df_to_vectorize, 'text')
# # Extract word embeddings
# word_embeddings_list = spacy_extractor.word_feature_scores()
# word_embeddings_list[0]

In [5]:
# Example DataFrame
tfidf_extractor = TfidfFeatureExtraction(df_to_vectorize, 'text')
tfidf_features = tfidf_extractor.word_feature_extraction()
tfidf_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (2, 7)>

In [7]:
# Convert sparse TF-IDF features to a dense format
tfidf_dense_features = tfidf_features.toarray()
tfidf_dense_features

array([[0.        , 0.        , 0.53404633, 0.37997836, 0.53404633,
        0.        , 0.53404633],
       [0.53404633, 0.53404633, 0.        , 0.37997836, 0.        ,
        0.53404633, 0.        ]])

In [6]:

spacy_extractor = SpacyFeatureExtraction(df_to_vectorize, 'text')
spacy_features = spacy_extractor.word_feature_extraction()
spacy_features

array([[-6.96985006e-01, -4.40641999e-01, -1.44374996e-01,
        -1.65606007e-01, -3.14744979e-01, -7.47375011e-01,
         1.66383997e-01,  3.35931510e-01,  1.50379986e-01,
         1.98654997e+00, -3.33660007e-01, -8.71580020e-02,
         8.09250101e-02,  7.31050000e-02, -3.58240008e-01,
         2.38570005e-01, -4.21800017e-02,  7.13353038e-01,
        -3.34714979e-01,  9.99915004e-02,  6.16209991e-02,
        -5.72021008e-02, -3.41550112e-02,  1.48135006e-01,
        -5.04624963e-01,  2.07925007e-01,  2.51746505e-01,
        -4.47109997e-01, -3.83850038e-02,  4.13289994e-01,
        -3.10169995e-01,  9.89185050e-02, -8.23150128e-02,
         1.71870500e-01,  3.02800596e-01,  3.68175000e-01,
        -2.87190020e-01, -1.73900127e-02,  6.24700040e-02,
         4.91345003e-02,  3.45794976e-01, -5.24850003e-02,
         1.55750006e-01, -3.42600048e-03, -1.89693511e-01,
        -2.57449895e-02,  1.14120003e-02,  4.95865017e-01,
         1.47327006e-01, -2.59820491e-01, -3.64130020e-0

In [ ]:
# Make sure spacy_features now is a proper 2D array:
spacy_features = spacy_extractor.word_feature_extraction()

# Now concatenating should work if they have the same number of rows
combined_features = np.hstack([tfidf_dense_features, spacy_features])

In [11]:
import numpy as np

# Now concatenating should work if they have the same number of rows
combined_features = np.hstack([tfidf_dense_features, spacy_features])
combined_features

array([[ 0.00000000e+00,  0.00000000e+00,  5.34046329e-01,
         3.79978362e-01,  5.34046329e-01,  0.00000000e+00,
         5.34046329e-01, -6.96985006e-01, -4.40641999e-01,
        -1.44374996e-01, -1.65606007e-01, -3.14744979e-01,
        -7.47375011e-01,  1.66383997e-01,  3.35931510e-01,
         1.50379986e-01,  1.98654997e+00, -3.33660007e-01,
        -8.71580020e-02,  8.09250101e-02,  7.31050000e-02,
        -3.58240008e-01,  2.38570005e-01, -4.21800017e-02,
         7.13353038e-01, -3.34714979e-01,  9.99915004e-02,
         6.16209991e-02, -5.72021008e-02, -3.41550112e-02,
         1.48135006e-01, -5.04624963e-01,  2.07925007e-01,
         2.51746505e-01, -4.47109997e-01, -3.83850038e-02,
         4.13289994e-01, -3.10169995e-01,  9.89185050e-02,
        -8.23150128e-02,  1.71870500e-01,  3.02800596e-01,
         3.68175000e-01, -2.87190020e-01, -1.73900127e-02,
         6.24700040e-02,  4.91345003e-02,  3.45794976e-01,
        -5.24850003e-02,  1.55750006e-01, -3.42600048e-0

In [10]:
tfidf_dense_features = tfidf_features.toarray()  # Confirming it's a 2D array